chore: combine into single job

diff --git a/.pipelines/client/e2e.yaml b/.pipelines/client/e2e.yaml
--- a/.pipelines/client/e2e.yaml
+++ b/.pipelines/client/e2e.yaml
@@ -19,10 +19,14 @@ pool:
 stages:
 - stage: E2E
   jobs:
-  - job: generate
-    displayName: Generate Required Variables
+  - job: e2e
+    displayName: Run E2E Tests
+    timeoutInMinutes: 0 # to account for long-running retries
     steps:
-      - checkout: none
+      - checkout: self
+        path: s
+        fetchTags: false
+        fetchDepth: 1
 
       - task: AzureCLI@2
         inputs:
@@ -34,7 +38,7 @@ stages:
             build_number_sum=$(echo -n "$(Build.BuildNumber)" | md5sum | tr -d "-" | tr -d " " | tr -d "\t")
             version="v0.0.0-${build_number_sum}"
             echo "generated client version for build $(Build.BuildNumber) = ${version}"
-            echo "##vso[task.setvariable variable=CLIENT_VERSION;isOutput=true;]${version}"
+            echo "##vso[task.setvariable variable=CLIENT_VERSION]${version}"
               
             web_endpoint=$(az storage account show -g $STORAGE_ACCOUNT_RESOURCE_GROUP -n $STORAGE_ACCOUNT_NAME --subscription $STORAGE_ACCOUNT_SUBSCRIPTION --query primaryEndpoints.web | tr -d \")
             linux_url="${web_endpoint}client/linux/amd64/${version}.tar.gz"
@@ -44,71 +48,51 @@ stages:
 
             toggle_overrides="custom-secure-tls-bootstrap-client-linux-binary-url=${linux_url},custom-secure-tls-bootstrap-client-windows-binary-url=${windows_url}"
             echo "Generated toggle override string = ${toggle_overrides}"
-            echo "##vso[task.setvariable variable=TOGGLE_OVERRIDES;isOutput=true;]${toggle_overrides}"
+            echo "##vso[task.setvariable variable=TOGGLE_OVERRIDES]${toggle_overrides}"
         env:
           STORAGE_ACCOUNT_SUBSCRIPTION: $(STORAGE_ACCOUNT_SUBSCRIPTION)
           STORAGE_ACCOUNT_RESOURCE_GROUP: $(STORAGE_ACCOUNT_RESOURCE_GROUP)
           STORAGE_ACCOUNT_NAME: $(STORAGE_ACCOUNT_NAME)
-        name: generate_variables
-        displayName: Generate Toggle Override String
+        condition: succeeded()
+        displayName: Generate Client Version String and Toggle Overrides
 
-  - job: build_and_upload_binaries
-    displayName: Build and Upload Client Binaries
-    dependsOn: generate
-    variables:
-      CLIENT_VERSION_STRING: $[dependencies.generate.outputs['generate_variables.CLIENT_VERSION']]
-    steps:
-    - checkout: self
-      path: s
-      fetchTags: false
-      fetchDepth: 1
+      - task: AzureCLI@2
+        condition: succeeded()
+        inputs:
+          azureSubscription: $(ARM_SERVICE_CONNECTION)
+          scriptType: bash
+          scriptLocation: inlineScript
+          inlineScript: |
+            set -euxo pipefail
+            cd ./client/ && ./hack/upload.sh
+        env:
+          OS: all # build linux + windows binaries
+          VERSION: $(CLIENT_VERSION)
+          STORAGE_ACCOUNT_SUBSCRIPTION: $(STORAGE_ACCOUNT_SUBSCRIPTION)
+          STORAGE_ACCOUNT_RESOURCE_GROUP: $(STORAGE_ACCOUNT_RESOURCE_GROUP)
+          STORAGE_ACCOUNT_NAME: $(STORAGE_ACCOUNT_NAME)
+        displayName: Build and Upload x86_64 Linux and Windows Binaries
 
-    - task: AzureCLI@2
-      inputs:
-        azureSubscription: $(ARM_SERVICE_CONNECTION)
-        scriptType: bash
-        scriptLocation: inlineScript
-        inlineScript: |
-          set -euxo pipefail
-          cd ./hack/ && ./upload.sh
-      env:
-        OS: all # build linux + windows binaries
-        VERSION: $(CLIENT_VERSION_STRING)
-        STORAGE_ACCOUNT_SUBSCRIPTION: $(STORAGE_ACCOUNT_SUBSCRIPTION)
-        STORAGE_ACCOUNT_RESOURCE_GROUP: $(STORAGE_ACCOUNT_RESOURCE_GROUP)
-        STORAGE_ACCOUNT_NAME: $(STORAGE_ACCOUNT_NAME)
-      displayName: Build and Upload x86_64 Linux and Windows Binaries
+      - bash: |
+          set -euo pipefail
+          az extension add -n azure-devops
+          echo $ADO_PAT | az devops login --organization=https://dev.azure.com/${ORGANIZATION} --verbose
+          az devops configure --defaults organization=https://dev.azure.com/${ORGANIZATION} project=${PROJECT}
+        env:
+          ADO_PAT: $(PAT-aksdevassistant)
+          ORGANIZATION: $(ORGANIZATION)
+          PROJECT: $(PROJECT)
+        condition: succeeded()
+        displayName: ADO Login
 
-  - job: run_e2e
-    displayName: Run E2E Tests
-    dependsOn: build_and_upload_binaries
-    timeoutInMinutes: 0 # to account for long-running retries
-    variables:
-      TOGGLE_OVERRIDE_STRING: $[dependencies.generate.outputs['generate_variables.TOGGLE_OVERRIDES']]
-    steps:
-    - checkout: self
-      path: s
-      fetchTags: false
-      fetchDepth: 1
-      
-    - bash: |
-        set -euo pipefail
-        az extension add -n azure-devops
-        echo $ADO_PAT | az devops login --organization=https://dev.azure.com/${ORGANIZATION} --verbose
-        az devops configure --defaults organization=https://dev.azure.com/${ORGANIZATION} project=${PROJECT}
-      env:
-        ADO_PAT: $(PAT-aksdevassistant)
-        ORGANIZATION: $(ORGANIZATION)
-        PROJECT: $(PROJECT)
-      displayName: ADO Login
-
-    - bash: /bin/bash .pipelines/client/scripts/run-pipeline.sh
-      env:
-        ADO_PAT: $(PAT-aksdevassistant)
-        AZURE_DEVOPS_EXT_PAT: $(PAT-aksdevassistant)
-        ADO_ORGANIZATION: $(ORGANIZATION)
-        ADO_PROJECT: $(PROJECT)
-        SUITE_ID: $(SECURE_TLS_BOOTSTRAPPING_CHECKIN_SUITE_ID)
-        ADDITIONAL_VARS: "VSTS_TOGGLE_OVERRIDES=$(ENABLE_SECURE_TLS_BOOTSTRAPPING_TOGGLE_SETTINGS),$(TOGGLE_OVERRIDE_STRING)"
-      displayName: Run Secure TLS Bootstrapping Check-in Tests
-      timeoutInMinutes: 0
+      - bash: /bin/bash .pipelines/client/scripts/run-pipeline.sh
+        env:
+          ADO_PAT: $(PAT-aksdevassistant)
+          AZURE_DEVOPS_EXT_PAT: $(PAT-aksdevassistant)
+          ADO_ORGANIZATION: $(ORGANIZATION)
+          ADO_PROJECT: $(PROJECT)
+          SUITE_ID: $(SECURE_TLS_BOOTSTRAPPING_CHECKIN_SUITE_ID)
+          ADDITIONAL_VARS: "VSTS_TOGGLE_OVERRIDES=$(ENABLE_SECURE_TLS_BOOTSTRAPPING_TOGGLE_SETTINGS),$(TOGGLE_OVERRIDES)"
+        condition: succeeded()
+        displayName: Run Secure TLS Bootstrapping Check-in Tests
+        timeoutInMinutes: 0
